# core/investment_company_impact.py

from dataclasses import dataclass


@dataclass(frozen=True)
class InvestmentCompanyImpact:
    """
    Year-1 incremental impact of an investment on the existing company.

    This object is the bridge between the multi-year investment analysis
    and the one-year projected CompanyState.

    It contains only incremental effects created by the investment.
    It does not contain the baseline company's values.
    """

    # Operating impact
    volume_delta: float
    revenue_delta: float
    variable_cost_delta: float
    fixed_opex_delta: float
    depreciation_delta: float

    # Balance-sheet / working-capital impact at the end of Year 1
    fixed_assets_delta: float
    ar_delta: float
    inventory_delta: float
    ap_delta: float
    nwc_delta: float

    # Cash-flow impact during Year 1
    operating_cash_flow_delta: float
    initial_capex: float
    initial_nwc_requirement: float
    initial_funding_requirement: float

    def __post_init__(self) -> None:
        numeric_fields = (
            "volume_delta",
            "revenue_delta",
            "variable_cost_delta",
            "fixed_opex_delta",
            "depreciation_delta",
            "fixed_assets_delta",
            "ar_delta",
            "inventory_delta",
            "ap_delta",
            "nwc_delta",
            "operating_cash_flow_delta",
            "initial_capex",
            "initial_nwc_requirement",
            "initial_funding_requirement",
        )

        for field_name in numeric_fields:
            value = getattr(self, field_name)

            if not isinstance(value, (int, float)):
                raise TypeError(
                    f"{field_name} must be numeric."
                )

    @property
    def project_cash_impact(self) -> float:
        """
        Net Year-1 cash impact of the investment.

        Initial CAPEX and initial NWC requirement are funding outflows.
        Operating cash flow is the Year-1 operating inflow.

        The Year-1 NWC balance is already represented by nwc_delta and
        therefore is not deducted a second time here.
        """

        return (
            self.operating_cash_flow_delta
            - self.initial_capex
            - self.initial_nwc_requirement
        )

    @property
    def ebit_delta(self) -> float:
        """
        Incremental Year-1 EBIT generated by the investment.
        """

        return (
            self.revenue_delta
            - self.variable_cost_delta
            - self.fixed_opex_delta
            - self.depreciation_delta
        )

    def summary(self) -> dict[str, float]:
        """
        Compact representation for execution traces and UI.
        """

        return {
            "volume_delta": self.volume_delta,
            "revenue_delta": self.revenue_delta,
            "variable_cost_delta": self.variable_cost_delta,
            "fixed_opex_delta": self.fixed_opex_delta,
            "depreciation_delta": self.depreciation_delta,
            "fixed_assets_delta": self.fixed_assets_delta,
            "ar_delta": self.ar_delta,
            "inventory_delta": self.inventory_delta,
            "ap_delta": self.ap_delta,
            "nwc_delta": self.nwc_delta,
            "operating_cash_flow_delta": self.operating_cash_flow_delta,
            "initial_capex": self.initial_capex,
            "initial_nwc_requirement": self.initial_nwc_requirement,
            "initial_funding_requirement": self.initial_funding_requirement,
            "ebit_delta": self.ebit_delta,
            "project_cash_impact": self.project_cash_impact,
        }
