from __future__ import annotations


# =========================================================
# CASH FRAGILITY DIAGNOSTIC ENGINE
# =========================================================

def calculate_cash_fragility(
    baseline_state,
    projected_state=None,
    financial_projection=None,
) -> dict:
    """
    Calculate liquidity and cash-fragility diagnostics.

    The diagnostic reads the canonical FinancialProjection
    when a projected state exists.

    Working-capital cash impact is NOT recalculated here.

    The FinancialEngine remains the single source of truth
    for financial impact.
    """

    # =====================================================
    # STATES
    # =====================================================

    baseline_drivers = baseline_state.drivers
    baseline_capital = baseline_state.capital_structure
    baseline_wc = baseline_state.working_capital

    projected_drivers = (
        projected_state.drivers
        if projected_state is not None
        else baseline_drivers
    )

    projected_capital = (
        projected_state.capital_structure
        if projected_state is not None
        else baseline_capital
    )

    projected_wc = (
        projected_state.working_capital
        if projected_state is not None
        else baseline_wc
    )

    # =====================================================
    # BASELINE CASH
    # =====================================================

    baseline_cash = float(
        baseline_drivers.opening_cash
    )

    # =====================================================
    # CANONICAL FINANCIAL IMPACT
    # =====================================================

    wc_cash_impact = 0.0
    fcfe_delta = 0.0

    if financial_projection is not None:

        impact = financial_projection.impact

        wc_cash_impact = float(
            impact.nwc_cash_impact_delta
        )

        fcfe_delta = float(
            impact.fcfe_delta
        )

    # =====================================================
    # PROJECTED CASH
    # =====================================================
    #
    # For the diagnostic, projected cash is the baseline
    # cash position plus the incremental cash generated by
    # the projected decision set.
    #
    # This is deliberately based on the canonical
    # FinancialEngine result rather than recalculating NWC.
    #
    # =====================================================

    projected_cash = (
        baseline_cash
        + fcfe_delta
    )

    # =====================================================
    # OPERATING DATA
    # =====================================================

    baseline_price = float(
        baseline_drivers.price
    )

    baseline_volume = float(
        baseline_drivers.volume
    )

    baseline_variable_cost = float(
        baseline_drivers.variable_cost_per_unit
    )

    baseline_fixed_opex = float(
        baseline_drivers.fixed_opex
    )

    baseline_interest = float(
        baseline_capital.annual_cash_interest_paid
    )

    baseline_debt_service = float(
        baseline_capital.annual_debt_service
    )

    # =====================================================
    # PROJECTED OPERATING DATA
    # =====================================================

    projected_price = float(
        projected_drivers.price
    )

    projected_volume = float(
        projected_drivers.volume
    )

    projected_variable_cost = float(
        projected_drivers.variable_cost_per_unit
    )

    projected_fixed_opex = float(
        projected_drivers.fixed_opex
    )

    projected_interest = float(
        projected_capital.annual_cash_interest_paid
    )

    projected_debt_service = float(
        projected_capital.annual_debt_service
    )

    # =====================================================
    # BASELINE CASH BURN
    # =====================================================

    baseline_revenue = (
        baseline_price
        * baseline_volume
    )

    baseline_variable_cost_total = (
        baseline_variable_cost
        * baseline_volume
    )

    baseline_cash_outflow = (
        baseline_variable_cost_total
        + baseline_fixed_opex
        + baseline_interest
        + baseline_debt_service
    )

    baseline_daily_burn = (
        baseline_cash_outflow / 365.0
    )

    # =====================================================
    # PROJECTED CASH BURN
    # =====================================================

    projected_variable_cost_total = (
        projected_variable_cost
        * projected_volume
    )

    projected_cash_outflow = (
        projected_variable_cost_total
        + projected_fixed_opex
        + projected_interest
        + projected_debt_service
    )

    projected_daily_burn = (
        projected_cash_outflow / 365.0
    )

    # =====================================================
    # CASH RUNWAY
    # =====================================================

    if baseline_daily_burn > 0:
        baseline_cash_runway = (
            baseline_cash
            / baseline_daily_burn
        )
    else:
        baseline_cash_runway = float("inf")

    if projected_daily_burn > 0:
        projected_cash_runway = (
            projected_cash
            / projected_daily_burn
        )
    else:
        projected_cash_runway = float("inf")

    # =====================================================
    # WORKING CAPITAL DAYS
    # =====================================================

    baseline_ccc = (
        float(baseline_wc.ar_days)
        + float(baseline_wc.inventory_days)
        - float(baseline_wc.ap_days)
    )

    projected_ccc = (
        float(projected_wc.ar_days)
        + float(projected_wc.inventory_days)
        - float(projected_wc.ap_days)
    )

    # =====================================================
    # RUNWAY AFTER CCC
    # =====================================================

    baseline_runway_after_cycle = (
        baseline_cash_runway
        - baseline_ccc
    )

    projected_runway_after_cycle = (
        projected_cash_runway
        - projected_ccc
    )

    # =====================================================
    # FRAGILITY SCORE
    # =====================================================

    score = 0.0

    # -----------------------------------------------------
    # PROJECTED CASH RUNWAY
    # -----------------------------------------------------

    if projected_cash_runway < 30:
        score += 40.0

    elif projected_cash_runway < 60:
        score += 25.0

    elif projected_cash_runway < 90:
        score += 10.0

    # -----------------------------------------------------
    # PROJECTED CCC
    # -----------------------------------------------------

    if projected_ccc > 120:
        score += 35.0

    elif projected_ccc > 90:
        score += 25.0

    elif projected_ccc > 60:
        score += 10.0

    # -----------------------------------------------------
    # PROJECTED RUNWAY AFTER CCC
    # -----------------------------------------------------

    if projected_runway_after_cycle < 0:
        score += 25.0

    elif projected_runway_after_cycle < 30:
        score += 15.0

    elif projected_runway_after_cycle < 60:
        score += 5.0

    fragility_score = min(
        100.0,
        max(0.0, score),
    )

    # =====================================================
    # STATUS
    # =====================================================

    if fragility_score >= 75:
        status = "Critical"

    elif fragility_score >= 50:
        status = "Fragile"

    elif fragility_score >= 25:
        status = "Watch"

    else:
        status = "Healthy"

    # =====================================================
    # INTERPRETATION
    # =====================================================

    if wc_cash_impact > 0:

        wc_message = (
            f"Working-capital changes release "
            f"€{wc_cash_impact:,.0f} of cash."
        )

    elif wc_cash_impact < 0:

        wc_message = (
            f"Working-capital changes absorb "
            f"€{abs(wc_cash_impact):,.0f} of cash."
        )

    else:

        wc_message = (
            "Working-capital changes have no "
            "net cash impact."
        )

    if status == "Healthy":

        interpretation = (
            "The company's liquidity position is "
            "relatively healthy. "
            f"{wc_message}"
        )

    elif status == "Watch":

        interpretation = (
            "The company shows some liquidity pressure. "
            f"{wc_message} "
            "Management should monitor cash runway and "
            "working-capital requirements closely."
        )

    elif status == "Fragile":

        interpretation = (
            "The company shows meaningful cash fragility. "
            f"{wc_message} "
            "The combination of cash runway and working "
            "capital requirements increases sensitivity "
            "to cash-flow shocks."
        )

    else:

        interpretation = (
            "The company shows severe liquidity fragility. "
            f"{wc_message} "
            "Cash runway and/or the working-capital cycle "
            "indicate potentially significant short-term "
            "funding risk."
        )

    # =====================================================
    # RESULT
    # =====================================================

    return {
        # Cash
        "cash_on_hand": projected_cash,
        "baseline_cash": baseline_cash,
        "projected_cash": projected_cash,

        # Burn
        "daily_burn_rate": projected_daily_burn,
        "daily_cash_requirement": projected_daily_burn,
        "daily_cash_req": projected_daily_burn,
        "baseline_daily_burn": baseline_daily_burn,

        # Runway
        "cash_runway": projected_cash_runway,
        "baseline_cash_runway": baseline_cash_runway,

        # Working capital
        "ccc_days": projected_ccc,
        "baseline_ccc_days": baseline_ccc,

        "runway_after_cycle": (
            projected_runway_after_cycle
        ),

        "baseline_runway_after_cycle": (
            baseline_runway_after_cycle
        ),

        # Financial impact
        "wc_cash_impact": wc_cash_impact,
        "fcfe_delta": fcfe_delta,

        # Score
        "fragility_score": fragility_score,
        "status": status,
        "interpretation": interpretation,
    }
