import plotly.graph_objects as go
import streamlit as st

from core.models import CompanyState
from core.financial_engine import FinancialProjection
from diagnostics.growth_funding import diagnose_growth_funding


def render_growth_funding_lab(
    baseline_state: CompanyState | None = None,
    projected_state: CompanyState | None = None,
    financial_projection: FinancialProjection | None = None,
):
    st.header("📈 Growth & Funding Diagnostic")

    st.caption(
        "Diagnosis of the funding and liquidity implications "
        "of the current projected CompanyState."
    )

    # =========================================================
    # VALIDATION
    # =========================================================

    if baseline_state is None:
        st.warning(
            "🔒 No company baseline available. "
            "Please lock the baseline first."
        )
        return

    if projected_state is None:
        st.warning(
            "No projected CompanyState is available."
        )
        return

    if financial_projection is None:
        st.warning(
            "No financial projection is available."
        )
        return

    # =========================================================
    # DIAGNOSTIC ENGINE
    # =========================================================

    res = diagnose_growth_funding(
        baseline_state=baseline_state,
        projected_state=projected_state,
        financial_projection=financial_projection,
    )

    # =========================================================
    # NO TOP-LINE IMPACT
    # =========================================================

    if abs(res.implied_growth_pct) < 0.01:

        st.info(
            "ℹ️ **No top-line impact detected from the current "
            "Decision Plan.**\n\n"
            "Use the Pricing or other operating Decision Labs "
            "to create a projected change in revenue and then "
            "return here to assess its funding implications."
        )

    # =========================================================
    # EXECUTIVE DIAGNOSIS
    # =========================================================

    st.subheader("🩺 Decision Impact Findings")

    m1, m2, m3, m4 = st.columns(4)

    # ---------------------------------------------------------
    # Revenue
    # ---------------------------------------------------------

    m1.metric(
        "Projected Revenue",
        f"€{res.projected_revenue:,.0f}",
        delta=(
            f"{res.implied_growth_pct:+.1f}% "
            f"(€{res.additional_revenue:+,.0f})"
        ),
    )

    # ---------------------------------------------------------
    # Working Capital
    # ---------------------------------------------------------

    m2.metric(
        "Working Capital Delta",
        f"€{res.working_capital_investment:,.0f}",
        delta=(
            "Cash Absorbed"
            if res.working_capital_investment > 0
            else "Cash Released"
        ),
        delta_color=(
            "inverse"
            if res.working_capital_investment > 0
            else "normal"
        ),
    )

    # ---------------------------------------------------------
    # Internal Funding
    # ---------------------------------------------------------

    m3.metric(
        "Internal Funding Capacity",
        f"€{res.internal_funding_available:,.0f}",
        help=(
            "Positive projected FCFE generated by the "
            "Financial Engine after operating performance, "
            "working-capital movement and principal repayments."
        ),
    )

    # ---------------------------------------------------------
    # Funding Requirement
    # ---------------------------------------------------------

    m4.metric(
        "External Funding Requirement",
        f"€{res.additional_funding_required:,.0f}",
        delta=(
            "Self-Funded"
            if res.is_self_funded
            else "External Capital Needed"
        ),
        delta_color=(
            "normal"
            if res.is_self_funded
            else "inverse"
        ),
    )

    # =========================================================
    # DIAGNOSTIC ALERTS
    # =========================================================

    st.divider()

    if res.is_growth_trap:

        st.error(
            f"🚨 **DIAGNOSIS: Growth Trap Warning!**\n\n"
            f"The projected company remains profitable "
            f"with net profit of **€{res.projected_net_profit:,.0f}**, "
            f"but projected FCFE is **€{res.projected_fcf:,.0f}**. "
            f"The business therefore requires additional funding "
            f"despite being profitable."
        )

    elif not res.is_self_funded:

        st.warning(
            f"⚠️ **DIAGNOSIS: Funding Requirement Identified.**\n\n"
            f"The projected company generates insufficient "
            f"internal cash to support the projected financial "
            f"position. Estimated additional funding requirement: "
            f"**€{res.additional_funding_required:,.0f}**."
        )

    else:

        st.success(
            f"✅ **DIAGNOSIS: Cash-Supported Growth.**\n\n"
            f"The projected company generates sufficient "
            f"internal cash flow to remain self-funded under "
            f"the current Decision Plan."
        )

    # =========================================================
    # SUPPORTING METRICS
    # =========================================================

    st.divider()

    st.subheader("Financial Drivers")

    c1, c2, c3 = st.columns(3)

    c1.metric(
        "Net Profit",
        f"€{res.projected_net_profit:,.0f}",
        delta=f"€{res.net_profit_delta:+,.0f}",
    )

    c2.metric(
        "NWC Investment",
        f"€{res.working_capital_investment:,.0f}",
    )

    c3.metric(
        "Projected FCFE",
        f"€{res.projected_fcf:,.0f}",
    )

    # =========================================================
    # WATERFALL
    # =========================================================

    st.divider()

    st.subheader("💧 Cash Flow Breakdown")

    # The waterfall now uses canonical financial-engine
    # outputs instead of reconstructing FCF inside the UI.

    wc_investment = res.working_capital_investment
    projected_fcfe = res.projected_fcf

    fig = go.Figure(
        go.Waterfall(
            measure=[
                "relative",
                "relative",
                "total",
            ],
            x=[
                "Working Capital Movement",
                "Projected FCFE",
                "Net Cash Position",
            ],
            y=[
                -wc_investment,
                projected_fcfe,
                0,
            ],
            text=[
                f"€{-wc_investment:,.0f}",
                f"€{projected_fcfe:,.0f}",
                f"€{projected_fcfe - wc_investment:,.0f}",
            ],
            textposition="outside",
        )
    )

    fig.update_layout(
        height=380,
        margin=dict(
            l=20,
            r=20,
            t=30,
            b=20,
        ),
        yaxis_title="Amount (€)",
    )

    st.plotly_chart(
        fig,
        use_container_width=True,
    )
