import numpy as np
import streamlit as st

from core.investment_decision import InvestmentDecision

from tools.investment_decision import (
    CompanyStateContext,
    InvestmentAssumptions,
    evaluate_investment,
    calculate_exit_option,
    calculate_tornado_sensitivity,
)


# ============================================================================
# INVESTMENT DECISION LAB
# ============================================================================

def render_investment_decision_lab(
    baseline_state=None,
    decision_plan=None,
):

    st.title("📊 Investment Decision Lab")

    st.markdown(
        "Evaluate an investment using incremental cash flows, "
        "NPV, IRR, Payback and decision-driver sensitivity."
    )

    st.divider()

    # ========================================================================
    # BASELINE
    # ========================================================================

    if baseline_state is not None:

        baseline_price = float(
            baseline_state.drivers.price
        )

        baseline_variable_cost = float(
            baseline_state.drivers.variable_cost_per_unit
        )

        baseline_fixed_opex = float(
            baseline_state.drivers.fixed_opex
        )

        baseline_fixed_assets = float(
            baseline_state.drivers.fixed_assets
        )

        baseline_depreciation = float(
            baseline_state.drivers.depreciation
        )

        baseline_tax_rate = float(
            baseline_state.capital_structure.tax_rate
        )

        baseline_wacc = float(
            baseline_state.capital_structure.wacc
        )

        baseline_ar_days = float(
            baseline_state.working_capital.ar_days
        )

        baseline_inventory_days = float(
            baseline_state.working_capital.inventory_days
        )

        baseline_ap_days = float(
            baseline_state.working_capital.ap_days
        )

    else:

        baseline_price = 0.0
        baseline_variable_cost = 0.0
        baseline_fixed_opex = 0.0
        baseline_fixed_assets = 0.0
        baseline_depreciation = 0.0
        baseline_tax_rate = 0.0
        baseline_wacc = 0.0
        baseline_ar_days = 0.0
        baseline_inventory_days = 0.0
        baseline_ap_days = 0.0

    # ========================================================================
    # INVESTMENT INPUTS
    # ========================================================================

    col1, col2 = st.columns(2)

    with col1:

        initial_investment = st.number_input(
            "Initial CAPEX",
            min_value=0.0,
            value=0.0,
            step=10000.0,
            help="Initial capital expenditure of the investment.",
            key="investment_initial_investment",
        )

        project_years = st.number_input(
            "Project Years",
            min_value=1,
            value=5,
            step=1,
            key="investment_project_years",
        )

        units = st.number_input(
            "Year-1 Incremental Units",
            min_value=0.0,
            value=0.0,
            step=1000.0,
            help="Additional units generated by the investment.",
            key="investment_units",
        )

    with col2:

        depreciation_years = st.number_input(
            "Useful Life / Depreciation Years",
            min_value=1,
            value=10,
            step=1,
            help="Useful life of the new CAPEX.",
            key="investment_depreciation_years",
        )

        incremental_fixed_costs = st.number_input(
            "Year-1 Incremental Fixed Costs",
            min_value=0.0,
            value=0.0,
            step=1000.0,
            help=(
                "Additional fixed operating costs created "
                "by the investment. Existing company fixed "
                "opex is not entered again."
            ),
            key="investment_fixed_costs",
        )

        salvage_value = st.number_input(
            "Terminal Salvage Value",
            min_value=0.0,
            value=0.0,
            step=1000.0,
            key="investment_salvage_value",
        )

    # ========================================================================
    # COMPANY BASELINE
    # ========================================================================

    st.subheader("Company Baseline")

    c1, c2, c3, c4 = st.columns(4)

    with c1:

        st.metric(
            "Price / Unit",
            f"€{baseline_price:,.2f}",
        )

    with c2:

        st.metric(
            "Variable Cost / Unit",
            f"€{baseline_variable_cost:,.2f}",
        )

    with c3:

        st.metric(
            "Tax Rate",
            f"{baseline_tax_rate * 100:.1f}%",
        )

    with c4:

        st.metric(
            "WACC",
            f"{baseline_wacc * 100:.1f}%",
        )

    wc1, wc2, wc3 = st.columns(3)

    with wc1:

        st.metric(
            "AR Days",
            f"{baseline_ar_days:.0f}",
        )

    with wc2:

        st.metric(
            "Inventory Days",
            f"{baseline_inventory_days:.0f}",
        )

    with wc3:

        st.metric(
            "AP Days",
            f"{baseline_ap_days:.0f}",
        )

    st.caption(
        "Tax rate, WACC and working-capital policies are inherited "
        "from the locked company baseline and are not project-level "
        "assumptions."
    )

    # ========================================================================
    # GROWTH
    # ========================================================================

    st.subheader("Project Growth Assumptions")

    g1, g2, g3, g4 = st.columns(4)

    with g1:

        volume_growth = (
            st.number_input(
                "Annual Volume Growth %",
                value=0.0,
                step=1.0,
                key="investment_volume_growth",
            )
            / 100.0
        )

    with g2:

        price_growth = (
            st.number_input(
                "Annual Price Growth %",
                value=0.0,
                step=1.0,
                key="investment_price_growth",
            )
            / 100.0
        )

    with g3:

        variable_cost_growth = (
            st.number_input(
                "Annual Variable Cost Growth %",
                value=0.0,
                step=1.0,
                key="investment_variable_cost_growth",
            )
            / 100.0
        )

    with g4:

        fixed_cost_growth = (
            st.number_input(
                "Annual Fixed Cost Growth %",
                value=0.0,
                step=1.0,
                key="investment_fixed_cost_growth",
            )
            / 100.0
        )

    # ========================================================================
    # INVESTMENT ECONOMICS
    # ========================================================================

    st.subheader("Investment Economics")

    use_price_override = st.checkbox(
        "Investment uses a different selling price",
        key="investment_use_price_override",
    )

    price_override = None

    if use_price_override:

        price_override = st.number_input(
            "Investment Selling Price / Unit",
            min_value=0.0,
            value=float(baseline_price),
            step=0.10,
            key="investment_price_override",
        )

    use_vc_override = st.checkbox(
        "Investment uses a different variable cost",
        key="investment_use_vc_override",
    )

    variable_cost_override = None

    if use_vc_override:

        variable_cost_override = st.number_input(
            "Investment Variable Cost / Unit",
            min_value=0.0,
            value=float(baseline_variable_cost),
            step=0.10,
            key="investment_variable_cost_override",
        )

    # IMPORTANT:
    # Tax rate and WACC overrides intentionally do not exist here.
    # Both are inherited from the locked company baseline.

    # ========================================================================
    # FLEXIBILITY
    # ========================================================================

    st.subheader("Project Flexibility")

    allow_exit = st.checkbox(
        "Allow Exit after Year 1",
        help=(
            "Tests whether management can limit downside "
            "by stopping the investment after Year 1."
        ),
        key="investment_allow_exit",
    )

    exit_value = 0.0
    exit_cost = 0.0
    downside_volume_pct = 0.0

    if allow_exit:

        e1, e2, e3 = st.columns(3)

        with e1:

            exit_value = st.number_input(
                "Recoverable Exit Value",
                min_value=0.0,
                value=0.0,
                step=1000.0,
                key="investment_exit_value",
            )

        with e2:

            exit_cost = st.number_input(
                "Exit / Shutdown Cost",
                min_value=0.0,
                value=0.0,
                step=1000.0,
                key="investment_exit_cost",
            )

        with e3:

            downside_volume_pct = (
                st.number_input(
                    "Year-1 Volume Downside %",
                    min_value=0.0,
                    max_value=100.0,
                    value=20.0,
                    step=5.0,
                    key="investment_downside_volume",
                )
                / 100.0
            )

    # ========================================================================
    # EVALUATE
    # ========================================================================

    if st.button(
        "▶ Evaluate Investment",
        type="primary",
        use_container_width=True,
        key="evaluate_investment_button",
    ):

        context = CompanyStateContext(
            price=baseline_price,
            variable_cost_per_unit=baseline_variable_cost,
            fixed_costs=baseline_fixed_opex,
            tax_rate=baseline_tax_rate,
            wacc=baseline_wacc,
            ar_days=baseline_ar_days,
            inventory_days=baseline_inventory_days,
            ap_days=baseline_ap_days,
            fixed_assets=baseline_fixed_assets,
            depreciation=baseline_depreciation,
        )

        assumptions = InvestmentAssumptions(
            initial_investment=initial_investment,
            project_years=int(project_years),
            units=units,
            depreciation_years=int(depreciation_years),
            incremental_fixed_costs=incremental_fixed_costs,
            annual_volume_growth=volume_growth,
            annual_price_growth=price_growth,
            annual_variable_cost_growth=variable_cost_growth,
            annual_fixed_cost_growth=fixed_cost_growth,
            salvage_value=salvage_value,
            price_override=price_override,
            variable_cost_override=variable_cost_override,
            allow_exit_after_year_1=allow_exit,
            exit_value=exit_value,
            exit_cost=exit_cost,
        )

        result = evaluate_investment(
            assumptions,
            context,
        )

        # Store the latest evaluation so it survives Streamlit reruns.
        st.session_state["investment_result"] = result
        st.session_state["investment_assumptions"] = assumptions
        st.session_state["investment_context"] = context

    # ========================================================================
    # STORED RESULT
    # ========================================================================

    result = st.session_state.get(
        "investment_result"
    )

    if result is None:
        return

    assumptions = st.session_state.get(
        "investment_assumptions"
    )

    context = st.session_state.get(
        "investment_context"
    )

    # ========================================================================
    # RESULTS
    # ========================================================================

    st.divider()

    st.subheader("Investment Decision")

    r1, r2, r3 = st.columns(3)

    with r1:

        st.metric(
            "NPV",
            f"€{result.npv:,.0f}",
        )

    with r2:

        st.metric(
            "IRR",
            f"{result.irr * 100:.1f}%",
        )

    with r3:

        if np.isinf(result.payback_years):

            payback_text = "Not recovered"

        else:

            payback_text = (
                f"{result.payback_years:.2f} years"
            )

        st.metric(
            "Payback",
            payback_text,
        )

    # ========================================================================
    # DECISION SIGNAL
    # ========================================================================

    if result.npv > 0:

        st.success(
            "🟢 Positive NPV — the project creates "
            "value at the company's baseline WACC."
        )

    elif result.npv < 0:

        st.error(
            "🔴 Negative NPV — the project destroys "
            "value at the company's baseline WACC."
        )

    else:

        st.warning(
            "🟡 NPV is approximately zero — the project "
            "is value-neutral at the company's baseline WACC."
        )

    # ========================================================================
    # YEAR-1 COMPANY IMPACT
    # ========================================================================

    if result.year_1_impact is not None:

        impact = result.year_1_impact

        st.divider()

        st.subheader(
            "Year-1 Impact on Existing Company"
        )

        st.caption(
            "Incremental effect if the investment is accepted. "
            "This is not a separate company state."
        )

        i1, i2, i3, i4 = st.columns(4)

        with i1:

            st.metric(
                "Revenue Δ",
                f"€{impact.incremental_revenue:,.0f}",
            )

        with i2:

            st.metric(
                "Variable Cost Δ",
                f"€{impact.incremental_variable_cost:,.0f}",
            )

        with i3:

            st.metric(
                "Fixed Opex Δ",
                f"€{impact.incremental_fixed_costs:,.0f}",
            )

        with i4:

            st.metric(
                "EBIT Δ",
                f"€{impact.incremental_ebit:,.0f}",
            )

        i5, i6, i7, i8 = st.columns(4)

        with i5:

            st.metric(
                "Depreciation Δ",
                f"€{impact.incremental_depreciation:,.0f}",
            )

        with i6:

            st.metric(
                "Net Profit Δ",
                f"€{impact.incremental_net_profit:,.0f}",
            )

        with i7:

            st.metric(
                "NWC Δ",
                f"€{impact.incremental_nwc:,.0f}",
            )

        with i8:

            st.metric(
                "Operating CF Δ",
                f"€{impact.incremental_operating_cash_flow:,.0f}",
            )

        st.subheader("Funding Requirement")

        f1, f2, f3 = st.columns(3)

        with f1:

            st.metric(
                "Initial CAPEX",
                f"€{impact.initial_capex:,.0f}",
            )

        with f2:

            st.metric(
                "Incremental NWC Requirement",
                f"€{impact.initial_nwc_requirement:,.0f}",
            )

        with f3:

            st.metric(
                "Initial Funding Requirement",
                f"€{impact.initial_funding_requirement:,.0f}",
            )

    # ========================================================================
    # PROJECT FLEXIBILITY
    # ========================================================================

    if allow_exit:

        exit_analysis = calculate_exit_option(
            assumptions,
            context,
            downside_volume_pct=downside_volume_pct,
        )

        st.divider()

        st.subheader("Project Flexibility")

        st.caption(
            f"Downside test: Year-1 volume "
            f"{downside_volume_pct * 100:.0f}% below plan."
        )

        x1, x2, x3 = st.columns(3)

        with x1:

            st.metric(
                "Continue Value",
                f"€{exit_analysis['downside_continue_value']:,.0f}",
            )

        with x2:

            st.metric(
                "Exit Value",
                f"€{exit_analysis['downside_exit_value']:,.0f}",
            )

        with x3:

            st.metric(
                "Value of Flexibility",
                f"€{exit_analysis['value_of_flexibility']:,.0f}",
            )

        if exit_analysis["value_of_flexibility"] > 0:

            st.success(
                "💡 Under the downside scenario, "
                "the ability to exit after Year 1 has economic value."
            )

        else:

            st.caption(
                "Under this downside scenario, continuing "
                "the project has at least as much value as exiting."
            )

    # ========================================================================
    # YEARLY CASH FLOWS
    # ========================================================================

    st.divider()

    st.subheader("Project Cash Flow")

    rows = []

    for year in result.yearly_cash_flows:

        rows.append(
            {
                "Year": year.year,
                "Units": year.units,
                "Price": year.price,
                "Revenue": year.revenue,
                "Variable Cost": year.variable_cost_total,
                "Incremental Fixed Costs": (
                    year.incremental_fixed_costs
                ),
                "Depreciation": year.depreciation,
                "EBIT": year.operating_profit,
                "Tax": year.tax,
                "Operating Cash Flow": (
                    year.operating_cash_flow
                ),
                "Incremental NWC": year.incremental_nwc,
                "Working Capital Cash Flow": (
                    year.working_capital_cash_flow
                ),
                "Salvage": year.salvage_value,
                "Project Cash Flow": year.project_cash_flow,
            }
        )

    st.dataframe(
        rows,
        use_container_width=True,
        hide_index=True,
    )

    # ========================================================================
    # TORNADO
    # ========================================================================

    st.divider()

    st.subheader(
        "Decision Drivers — NPV Sensitivity"
    )

    tornado = calculate_tornado_sensitivity(
        assumptions,
        context,
    )

    if tornado:

        tornado_rows = [
            {
                "Driver": t.driver_name,
                "Low NPV": t.low_npv,
                "Base NPV": t.base_npv,
                "High NPV": t.high_npv,
                "Impact Range": t.range_span,
            }
            for t in tornado
        ]

        st.dataframe(
            tornado_rows,
            use_container_width=True,
            hide_index=True,
        )

        st.caption(
            "WACC remains a decision-driver sensitivity because "
            "it affects investment valuation. It is inherited from "
            "the locked company baseline and is not a project assumption."
        )

    else:

        st.caption(
            "No non-zero drivers available for sensitivity analysis."
        )

    # ========================================================================
    # ADD TO DECISION PLAN
    # ========================================================================

    st.divider()

    st.subheader("Decision Plan")

    st.caption(
        "Evaluation does not automatically add the investment to "
        "the Decision Plan. Add it explicitly when you want the "
        "investment to become part of the company decision scenario."
    )

    if decision_plan is not None:

        if st.button(
            "➕ Add Investment to Decision Plan",
            type="secondary",
            use_container_width=True,
            key="add_investment_to_plan_button",
        ):

            investment_decision = InvestmentDecision.create(
                decision_id="investment_1",
                name="New Investment",
                description=(
                    "Investment project evaluated against the locked "
                    "company baseline."
                ),
                assumptions=assumptions,
            )

            st.session_state.decision_plan = decision_plan.add(
                investment_decision
            )

            st.success(
                "Investment was added to the Decision Plan."
            )

    else:

        st.info(
            "Decision Plan is not available in the current app context."
        )
