import math

import streamlit as st

from tools.replacement_analysis import (
    ReplacementAssumptions,
    evaluate_replacement,
)


# ============================================================================
# REPLACEMENT ANALYSIS
# ============================================================================

def render_replacement_analysis(
    baseline_state=None,
):

    st.title("🔄 Replacement Analysis")

    st.markdown(
        "Evaluate whether replacing an existing machine creates "
        "more value than keeping it, using incremental cash flows."
    )

    st.divider()

    # ========================================================================
    # BASELINE
    # ========================================================================

    if baseline_state is not None:

        baseline_tax_rate = float(
            baseline_state.capital_structure.tax_rate
        )

        baseline_wacc = float(
            baseline_state.capital_structure.wacc
        )

    else:

        baseline_tax_rate = 0.0
        baseline_wacc = 0.0

    # ========================================================================
    # EXISTING MACHINE
    # ========================================================================

    st.subheader("Existing Machine")

    old1, old2 = st.columns(2)

    with old1:

        old_market_value = st.number_input(
            "Current Market Value",
            min_value=0.0,
            value=0.0,
            step=500.0,
            help=(
                "Current amount the company could receive "
                "by selling the existing machine today."
            ),
        )

    with old2:

        old_book_value = st.number_input(
            "Current Book Value",
            min_value=0.0,
            value=0.0,
            step=500.0,
            help=(
                "Current accounting book value of the existing machine."
            ),
        )

    old3, old4 = st.columns(2)

    with old3:

        old_annual_depreciation = st.number_input(
            "Current Annual Depreciation",
            min_value=0.0,
            value=0.0,
            step=100.0,
        )

    with old4:

        old_terminal_value = st.number_input(
            "Old Machine Terminal Value if Kept",
            min_value=0.0,
            value=0.0,
            step=500.0,
            help=(
                "Expected value of the old machine at the end "
                "of the comparison period if it is kept."
            ),
        )

    # ========================================================================
    # NEW MACHINE
    # ========================================================================

    st.subheader("Replacement Machine")

    new1, new2 = st.columns(2)

    with new1:

        new_machine_cost = st.number_input(
            "Purchase Cost",
            min_value=0.0,
            value=0.0,
            step=1000.0,
        )

        useful_life = st.number_input(
            "Useful Life / Years",
            min_value=1,
            value=5,
            step=1,
        )

    with new2:

        operating_cost_reduction = st.number_input(
            "Annual Operating Cost Reduction",
            min_value=0.0,
            value=0.0,
            step=500.0,
            help=(
                "Annual reduction in relevant operating costs "
                generated by the replacement."
            ),
        )

        residual_pct = (
            st.number_input(
                "Residual Value %",
                min_value=0.0,
                max_value=100.0,
                value=5.0,
                step=1.0,
                help=(
                    "Residual value as a percentage of the "
                    "new machine purchase cost."
                ),
            )
            / 100.0
        )

    # ========================================================================
    # COMPANY
    # ========================================================================

    st.subheader("Company Assumptions")

    c1, c2, c3 = st.columns(3)

    with c1:

        tax_rate = (
            st.number_input(
                "Tax Rate %",
                min_value=0.0,
                max_value=100.0,
                value=float(
                    baseline_tax_rate * 100.0
                ),
                step=1.0,
            )
            / 100.0
        )

    with c2:

        wacc = (
            st.number_input(
                "WACC %",
                min_value=0.0,
                max_value=100.0,
                value=float(
                    baseline_wacc * 100.0
                ),
                step=0.5,
            )
            / 100.0
        )

    with c3:

        increase_nwc = st.number_input(
            "Increase in Net Operating WC",
            min_value=0.0,
            value=0.0,
            step=500.0,
        )

    st.caption(
        "New-machine depreciation uses the straight-line method. "
        "Residual value defaults to 5% of purchase cost."
    )

    # ========================================================================
    # EVALUATE
    # ========================================================================

    if st.button(
        "▶ Evaluate Replacement",
        type="primary",
        use_container_width=True,
    ):

        assumptions = ReplacementAssumptions(
            new_machine_cost=new_machine_cost,
            new_machine_life=int(useful_life),
            annual_operating_cost_reduction=(
                operating_cost_reduction
            ),
            new_machine_residual_pct=residual_pct,
            old_machine_market_value=old_market_value,
            old_machine_book_value=old_book_value,
            old_machine_annual_depreciation=(
                old_annual_depreciation
            ),
            old_machine_terminal_value_if_kept=(
                old_terminal_value
            ),
            increase_nwc=increase_nwc,
            tax_rate=tax_rate,
            wacc=wacc,
        )

        result = evaluate_replacement(
            assumptions
        )

        # ====================================================================
        # DECISION
        # ====================================================================

        st.divider()

        st.subheader("Replacement Decision")

        r1, r2, r3, r4 = st.columns(4)

        with r1:

            st.metric(
                "NPV",
                f"€{result.npv:,.0f}",
            )

        with r2:

            st.metric(
                "IRR",
                f"{result.irr * 100:.2f}%",
            )

        with r3:

            st.metric(
                "MIRR",
                f"{result.mirr * 100:.2f}%",
            )

        with r4:

            if math.isinf(
                result.payback_years
            ):

                payback_text = "Not recovered"

            else:

                payback_text = (
                    f"{result.payback_years:.2f} years"
                )

            st.metric(
                "Payback",
                payback_text,
            )

        if result.npv > 0:

            st.success(
                "🟢 Replace — the replacement creates "
                "positive value at the selected WACC."
            )

        elif result.npv < 0:

            st.error(
                "🔴 Keep — the replacement destroys "
                "value at the selected WACC."
            )

        else:

            st.warning(
                "🟡 Indifferent — replacement NPV is approximately zero."
            )

        # ====================================================================
        # INVESTMENT STRUCTURE
        # ====================================================================

        st.divider()

        st.subheader("Initial Replacement Outlay")

        a1, a2, a3, a4 = st.columns(4)

        with a1:

            st.metric(
                "New Machine",
                f"€{new_machine_cost:,.0f}",
            )

        with a2:

            st.metric(
                "After-Tax Old Machine Proceeds",
                f"€{result.after_tax_old_machine_sale_proceeds:,.0f}",
            )

        with a3:

            st.metric(
                "NWC Increase",
                f"€{increase_nwc:,.0f}",
            )

        with a4:

            st.metric(
                "Initial Incremental Outlay",
                f"€{result.initial_incremental_outlay:,.0f}",
            )

        # ====================================================================
        # DEPRECIATION
        # ====================================================================

        st.divider()

        st.subheader("Depreciation")

        d1, d2, d3 = st.columns(3)

        with d1:

            st.metric(
                "Residual Value",
                f"€{result.new_machine_residual_value:,.0f}",
            )

        with d2:

            st.metric(
                "Depreciable Base",
                f"€{result.new_machine_depreciable_base:,.0f}",
            )

        with d3:

            st.metric(
                "Annual Straight-Line Depreciation",
                f"€{result.annual_new_depreciation:,.0f}",
            )

        st.caption(
            "Depreciation = (Purchase Cost − Residual Value) / Useful Life."
        )

        # ====================================================================
        # OLD MACHINE TAX EFFECT
        # ====================================================================

        if abs(result.old_sale_tax_effect) > 0:

            st.info(
                f"Tax effect from selling the old machine: "
                f"€{result.old_sale_tax_effect:,.0f}"
            )

        # ====================================================================
        # CASH FLOW TABLE
        # ====================================================================

        st.divider()

        st.subheader("Incremental Cash Flow Schedule")

        rows = [
            {
                "Year": 0,
                "Operating Savings": 0,
                "New Depreciation": 0,
                "Old Depreciation": 0,
                "Δ Depreciation": 0,
                "Depreciation Tax Shield": 0,
                "After-Tax Operating Savings": 0,
                "Terminal Value": 0,
                "NWC Recovery": 0,
                "Incremental CF": (
                    result.initial_incremental_outlay
                ),
                "Cumulative CF": (
                    result.initial_incremental_outlay
                ),
            }
        ]

        for year in result.yearly_cash_flows:

            rows.append(
                {
                    "Year": year.year,
                    "Operating Savings": round(
                        year.operating_cost_savings,
                        0,
                    ),
                    "New Depreciation": round(
                        year.new_depreciation,
                        0,
                    ),
                    "Old Depreciation": round(
                        year.old_depreciation,
                        0,
                    ),
                    "Δ Depreciation": round(
                        year.depreciation_change,
                        0,
                    ),
                    "Depreciation Tax Shield": round(
                        year.tax_shield_from_depreciation,
                        0,
                    ),
                    "After-Tax Operating Savings": round(
                        year.after_tax_operating_savings,
                        0,
                    ),
                    "Terminal Value": round(
                        year.terminal_value,
                        0,
                    ),
                    "NWC Recovery": round(
                        year.nwc_recovery,
                        0,
                    ),
                    "Incremental CF": round(
                        year.incremental_cash_flow,
                        0,
                    ),
                    "Cumulative CF": round(
                        year.cumulative_cash_flow,
                        0,
                    ),
                }
            )

        st.dataframe(
            rows,
            use_container_width=True,
            hide_index=True,
        )
