import sys
from pathlib import Path

root_dir = Path(__file__).resolve().parent.parent
if str(root_dir) not in sys.path:
    sys.path.insert(0, str(root_dir))

import streamlit as st

from diagnostics.substitute_products import (
    calculate_substitute_price_increase_impact,
)


def _get_price(baseline_state):
    try:
        return float(baseline_state.drivers.price)
    except AttributeError:
        return float(getattr(baseline_state, "price", 150.0))


def _get_variable_cost(baseline_state):
    try:
        return float(
            baseline_state.drivers.variable_cost_per_unit
        )
    except AttributeError:
        return float(
            getattr(baseline_state, "variable_cost", 100.0)
        )


def _format_euro(value):
    return f"€{float(value):,.2f}"


def render_substitute_products_lab(baseline_state):
    """
    Diagnostic:
    How resilient is a price increase when customers may switch
    to substitute products?
    """

    st.title("🔄 Substitute Products Diagnostic")

    st.markdown(
        """
        **What happens if I increase my price and some customers
        switch to substitute products?**

        This diagnostic estimates how much switching the business
        can absorb before the additional contribution from the
        higher price is offset.
        """
    )

    price = _get_price(baseline_state)
    variable_cost = _get_variable_cost(baseline_state)
    current_profit = price - variable_cost

    st.subheader("Current Main Product")

    c1, c2, c3 = st.columns(3)

    c1.metric("Current Price", _format_euro(price))
    c2.metric("Variable Cost", _format_euro(variable_cost))
    c3.metric("Contribution / Unit", _format_euro(current_profit))

    st.divider()

    st.subheader("1. Price Decision")

    price_increase_pct = st.number_input(
        "Price increase (%)",
        min_value=0.0,
        max_value=100.0,
        value=10.0,
        step=1.0,
        key="substitute_price_increase",
    )

    st.subheader("2. Substitute Products")

    st.caption(
        "Add the expected profit generated by the substitute "
        "and the probability that a customer switches to it."
    )

    product_count = st.number_input(
        "Number of substitute products",
        min_value=1,
        max_value=10,
        value=2,
        step=1,
        key="substitute_product_count",
    )

    substitute_data = []

    for i in range(int(product_count)):
        c1, c2 = st.columns(2)

        with c1:
            profit = st.number_input(
                f"Substitute {i + 1} — Profit per purchase (€)",
                min_value=0.0,
                value=15.0,
                step=5.0,
                key=f"substitute_profit_{i}",
            )

        with c2:
            probability_pct = st.number_input(
                f"Substitute {i + 1} — Switching probability (%)",
                min_value=0.0,
                max_value=100.0,
                value=10.0,
                step=5.0,
                key=f"substitute_probability_{i}",
            )

        substitute_data.append(
            (profit, probability_pct / 100.0)
        )

    st.divider()

    if st.button(
        "🔍 Analyze Substitute Risk",
        use_container_width=True,
        key="analyze_substitute_products",
    ):
        result = calculate_substitute_price_increase_impact(
            current_price=price,
            price_increase_pct=price_increase_pct,
            current_profit_per_unit=current_profit,
            substitute_data=substitute_data,
        )

        if result is None:
            st.error(
                "The diagnostic cannot be calculated with the "
                "current baseline assumptions."
            )
            return

        st.session_state[
            "substitute_products_result"
        ] = result

    result = st.session_state.get(
        "substitute_products_result"
    )

    if result is None:
        return

    st.divider()
    st.subheader("🏁 Result")

    c1, c2, c3 = st.columns(3)

    c1.metric(
        "Price After Increase",
        _format_euro(
            result["price_after_increase"]
        ),
    )

    c2.metric(
        "Additional Contribution / Unit",
        _format_euro(
            result["additional_profit_per_unit"]
        ),
    )

    c3.metric(
        "Expected Substitute Effect",
        _format_euro(
            result["expected_substitute_profit"]
        ),
    )

    st.divider()

    break_even = result["break_even_switching_rate"]

    if break_even is None:
        st.info(
            "A meaningful break-even switching rate cannot be "
            "determined under the current assumptions."
        )
    elif break_even >= 100:
        st.success(
            f"""
            **The price increase has strong resilience under the
            current assumptions.**

            The additional contribution can absorb up to
            approximately **{break_even:.1f}%** switching before
            reaching the estimated threshold.
            """
        )
    else:
        st.warning(
            f"""
            The estimated break-even switching rate is
            **{break_even:.1f}%**.

            Above this level, the contribution gained from the
            price increase is no longer sufficient to offset the
            expected economics of substitution.
            """
        )

    if result["resilience_status"] == "Resilient":
        st.success(
            "Overall assessment: **Resilient**"
        )
    elif result["resilience_status"] == "At Threshold":
        st.warning(
            "Overall assessment: **At Threshold**"
        )
    else:
        st.error(
            "Overall assessment: **Vulnerable**"
        )

    with st.expander(
        "ℹ️ How this diagnostic works",
        expanded=False,
    ):
        st.markdown(
            """
            The diagnostic compares the incremental contribution
            created by the higher price with the expected economic
            effect of customers moving to substitute products.

            For each substitute:

            `Profit per substitute × Switching probability`

            gives the expected substitute contribution.

            The model then estimates the switching level at which
            the additional contribution from the price increase
            is no longer sufficient.
            """
        )
